CREATE TABLE CONSUMERS (
    ID INT PRIMARY KEY,
    NAME NVARCHAR(255),
    BIRTHDAY DATE,
    PHONE NVARCHAR(20),
    EMAIL NVARCHAR(255),
    CITY NVARCHAR(100),
    UF CHAR(2),
    ADDRESS NVARCHAR(255),
    NR_DOC CHAR(14),
    JOB_TITLE NVARCHAR(100),
    INSERT_DATE DATETIME,
    LAST_UPDATE DATETIME
);

CREATE TABLE STORES (
    ID INT PRIMARY KEY,
    NAME NVARCHAR(255),
    PHONE NVARCHAR(20),
    CITY NVARCHAR(100),
    UF CHAR(2),
    ADDRESS NVARCHAR(255),
    NR_DOC CHAR(18),
    INSERT_DATE DATETIME,
    LAST_UPDATE DATETIME
);

CREATE TABLE PRODUCTS (
    ID INT PRIMARY KEY,
    NAME NVARCHAR(255),
    CATEGORY NVARCHAR(100),
    SUBCATEGORY NVARCHAR(100),
    PRICE DECIMAL(18, 2),
    INSERT_DATE DATETIME,
    LAST_UPDATE DATETIME
);

DROP TABLE IF EXISTS SALES;
DROP TABLE IF EXISTS SALE_ITEMS;

CREATE TABLE SALE_ITEMS(
    ITEM_ID INT PRIMARY KEY,
    PRODUCT_ID INT FOREIGN KEY REFERENCES PRODUCTS(ID),
    AMOUNT INT NOT NULL,
    -- SALE_VALUE_UNI DECIMAL(10,2) NOT NULL,
    -- SALE_VALUE_TOTAL DECIMAL(10,2) NOT NULL,
    DISCOUNTED DECIMAL(2,2) NOT NULL,
    INSERT_DATE DATETIME
);

CREATE TABLE SALES(
    SALE_ID INT PRIMARY KEY,
    ITEM_ID INT FOREIGN KEY REFERENCES SALE_ITEMS(ITEM_ID),
    STORE_ID INT FOREIGN KEY REFERENCES STORES(ID),
    CONSUMER_ID INT FOREIGN KEY REFERENCES CONSUMERS(ID),
    SALE_DATE DATETIME
);