SELECT
  *
FROM ALL_TABLES
ORDER BY NUM_ROWS DESC;


SELECT
  OWNER,
  TABLE_NAME,
  TABLESPACE_NAME,
  NUM_ROWS,
  LAST_ANALYZED
FROM ALL_TABLES
WHERE
  OWNER = ''
  AND TABLE_NAME = ''
ORDER BY NUM_ROWS DESC;


SELECT
  *
FROM ALL_TAB_MODIFICATIONS
WHERE 
  TABLE_NAME = ''
ORDER BY TIMESTAMP;


SELECT
  OWNER,
  TABLE_NAME,
  COLUMN_NAME,
  DATA_TYPE,
  DATA_LENGTH,
  DATA_PRECISION,
  NULLABLE,
  CHARACTER_SET_NAME
FROM ALL_TAB_COLS
WHERE
  TABLE_NAME = ''
ORDER BY DATA_TYPE, COLUMN_NAME;


SELECT
  ROUND(SUM(BYTES) / 1024 / 1024 / 1024, 2) AS SPACE_GB
FROM DBA_SEGMENTS
WHERE
  SEGMENT_NAME = 'TABLE_NAME';


SELECT
  TB.OWNER,
  TB.TABLE_NAME,
  TB.TABLESPACE_NAME,
  TB.LAST_ANALYZED,
  TB.NUM_ROWS,
  ROUND(SEG.BYTES / 1024 / 1024 / 1024, 2) AS SPACE_GB
FROM ALL_TABLES TB
INNER JOIN DBA_SEGMENTS SEG ON SEG.SEGMENT_NAME = TB.TABLE_NAME
WHERE
  TB.OWNER = ''
ORDER BY
  TB.NUM_ROWS DESC;


SELECT 
    A.OWNER,
    A.CONSTRAINT_NAME,
    A.TABLE_NAME,
    A.COLUMN_NAME,
    B.CONSTRAINT_NAME,
    B.CONSTRAINT_TYPE
FROM all_cons_columns A
INNER JOIN all_constraints B ON A.CONSTRAINT_NAME = B.CONSTRAINT_NAME
WHERE 
  B.CONSTRAINT_TYPE = 'P'
ORDER BY A.TABLE_NAME; 


SELECT 
  OBJECT_TYPE, 
  COUNT(*) AS NUM_OBJECTS
FROM ALL_OBJECTS
GROUP BY OBJECT_TYPE
ORDER BY OBJECT_TYPE;


SELECT 
  TABLE_NAME, 
  ROUND(SUM(BYTES) / 1024 / 1024, 2) AS SPACE_MB
FROM USER_SEGMENTS
WHERE SEGMENT_TYPE = 'TABLE'
GROUP BY TABLE_NAME
ORDER BY SPACE_MB DESC;

SELECT 
  TABLE_NAME, 
  ROUND((SUM(BYTES) / 1024 / 1024), 2) AS SIZE_MB
FROM USER_TABLES
GROUP BY TABLE_NAME
ORDER BY SIZE_MB DESC;