USE ssisdb

SELECT 
  NAME,
  created_by_name,
  created_time
FROM internal.folders;

SELECT 
  P.NAME AS PROJECT_NAME,
  F.NAME AS FOLDER_NAME,
  P.deployed_by_name,
  P.created_time,
  P.last_deployed_time
FROM internal.projects P
  INNER JOIN internal.folders F ON P.folder_id = F.folder_id;

SELECT 
  J.NAME  AS JOB_NAME,
  P.NAME  AS OWNER_NAME,
  CASE
    WHEN J.enabled = 1 THEN 'ATIVO'
      ELSE 'INATIVO'
  END AS STATUS,
  SC.NAME AS FREQ,
  Stuff(Stuff(RIGHT('000000' + CONVERT(VARCHAR(6), S.next_run_time), 6), 3, 0, ':'), 6, 0, ':') AS TIME
FROM msdb.dbo.sysjobs J
  INNER JOIN sys.server_principals P ON J.owner_sid = P.sid
  INNER JOIN msdb.dbo.sysjobschedules S ON J.job_id = S.job_id
  INNER JOIN msdb.dbo.sysschedules SC ON S.schedule_id = SC.schedule_id
ORDER  BY J.NAME;


USE msdb;

SELECT
    J.NAME AS JOB_NAME,
    S.step_id AS STEP_ID,
    S.step_name AS STEP_NAME,
    S.subsystem AS SUBSYSTEM,
	--P.name AS PROXY_NAME,
	J.description,
	S.command AS COMMAND,
	CONVERT(DATE, CONVERT(CHAR(8), S.NEXT_RUN_DATE, 112))
FROM dbo.sysjobs J
INNER JOIN dbo.sysjobsteps S ON J.job_id = S.job_id
LEFT JOIN dbo.sysproxies P ON S.proxy_id = P.proxy_id
ORDER BY
    J.name, STEP_ID

-----

USE MSDB;

SELECT
    JOB.NAME AS JOB_NAME,
    STEP.STEP_ID AS STEP_ID,
    STEP.STEP_NAME AS STEP_NAME,
    STEP.SUBSYSTEM AS SUBSYSTEM,
    USR.NAME  AS OWNER_NAME,
	--P.NAME AS PROXY_NAME,
    CASE
        WHEN JOB.ENABLED = 1 THEN 'ATIVO'
        ELSE 'INATIVO'
    END AS STATUS,
    SC.NAME AS FREQ,
	STUFF(STUFF(RIGHT('000000' + CONVERT(VARCHAR(6), S.NEXT_RUN_TIME), 6), 3, 0, ':'), 6, 0, ':') AS TIME,
	JOB.DESCRIPTION,
	STEP.COMMAND AS COMMAND
FROM DBO.SYSJOBS JOB
    INNER JOIN DBO.SYSJOBSTEPS STEP ON JOB.JOB_ID = STEP.JOB_ID
    LEFT JOIN DBO.SYSPROXIES PROXY ON STEP.PROXY_ID = PROXY.PROXY_ID
    INNER JOIN SYS.SERVER_PRINCIPALS USR ON JOB.OWNER_SID = USR.SID
    INNER JOIN MSDB.DBO.SYSJOBSCHEDULES S ON JOB.JOB_ID = S.JOB_ID
    INNER JOIN MSDB.DBO.SYSSCHEDULES SC ON S.SCHEDULE_ID = SC.SCHEDULE_ID
ORDER BY
    JOB.NAME, STEP_ID



------- QUERY MASTER

USE MSDB;

SELECT
    JOB.NAME AS JOB_NAME,
	CASE
        WHEN JOB.ENABLED = 1 THEN 'Ativo'
        ELSE 'Inativo'
    END AS STATUS,
	STUFF(STUFF(RIGHT('000000' + CONVERT(VARCHAR(6), S.NEXT_RUN_TIME), 6), 3, 0, ':'), 6, 0, ':') AS 'TRIGGER',
    STEP.STEP_ID AS STEP_ID,
    STEP.STEP_NAME AS STEP_NAME,
    STEP.SUBSYSTEM AS SUBSYSTEM,
	JOB.DESCRIPTION,
    USR.NAME AS OWNER_NAME,
	PROXY.NAME AS PROXY_NAME,
	STEP.COMMAND AS COMMAND,
	SC.NAME AS FREQ
FROM DBO.SYSJOBS JOB
    INNER JOIN DBO.SYSJOBSTEPS STEP ON JOB.JOB_ID = STEP.JOB_ID
    LEFT JOIN DBO.SYSPROXIES PROXY ON STEP.PROXY_ID = PROXY.PROXY_ID
    INNER JOIN SYS.SERVER_PRINCIPALS USR ON JOB.OWNER_SID = USR.SID
    INNER JOIN MSDB.DBO.SYSJOBSCHEDULES S ON JOB.JOB_ID = S.JOB_ID
    INNER JOIN MSDB.DBO.SYSSCHEDULES SC ON S.SCHEDULE_ID = SC.SCHEDULE_ID
ORDER BY
    JOB.NAME, STEP_ID


    